import { useState, useRef } from 'react';
import { toast } from 'sonner';
import { CLASS_SUBJECTS } from '@/lib/classSubjects';
import { generateDemoResult } from '@/lib/demoResults';

import BackButton from '@/components/portal/BackButton';
import ResultActions from '@/components/portal/ResultActions';
interface PortalProps { isDemo?: boolean; schoolName?: string; logoUrl?: string | null; onSearch?: (className: string, studentName: string) => Promise<any>; demoResult?: any; }
const GlassmorphismPortal = ({ isDemo = true, schoolName = "Peshawar Grammar School", logoUrl, onSearch, demoResult }: PortalProps) => {
  const [selectedClass, setSelectedClass] = useState(''); const [studentName, setStudentName] = useState(''); const [loading, setLoading] = useState(false); const [result, setResult] = useState<any>(demoResult || null); const [error, setError] = useState(''); const resultRef = useRef<HTMLDivElement>(null);
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); if (!selectedClass || !studentName) { toast.error('Please select a class and enter your name'); return; } setLoading(true); setError(''); setResult(null); if (isDemo) { setTimeout(() => { setResult(generateDemoResult(studentName, selectedClass)); setLoading(false); toast.success('Result loaded successfully!'); }, 1000); } else if (onSearch) { try { const r = await onSearch(selectedClass, studentName); if (r) { setResult(r); toast.success('Result loaded!'); } else { setError('No result found.'); } } catch { setError('An error occurred.'); } finally { setLoading(false); } } };
  return (
    <div className="min-h-screen relative overflow-hidden bg-gradient-to-br from-purple-400 via-pink-500 to-red-500">
      <PortalBranding variant="dark" /><BackButton variant="dark" />
      <div className="absolute inset-0 opacity-40 pointer-events-none"><div className="absolute top-20 left-10 sm:left-20 w-40 sm:w-72 h-40 sm:h-72 bg-white rounded-full mix-blend-multiply filter blur-xl"></div><div className="absolute top-40 right-10 sm:right-20 w-40 sm:w-72 h-40 sm:h-72 bg-yellow-300 rounded-full mix-blend-multiply filter blur-xl"></div><div className="absolute bottom-20 left-20 sm:left-40 w-40 sm:w-72 h-40 sm:h-72 bg-pink-300 rounded-full mix-blend-multiply filter blur-xl"></div></div>
      <main className="relative z-10 container mx-auto px-3 sm:px-4 pt-14 sm:pt-12 pb-20 max-w-3xl">
        <header className="text-center mb-6 sm:mb-12"><div className="backdrop-blur-md bg-white/10 border border-white/20 rounded-2xl sm:rounded-3xl p-4 sm:p-8 shadow-2xl">{logoUrl && <img src={logoUrl} alt={schoolName} className="h-20 w-20 mx-auto mb-4 rounded-full object-cover shadow-lg border-2 border-white/30" />}<h1 className="text-xl sm:text-5xl font-bold text-white mb-1 sm:mb-2 drop-shadow-lg">{schoolName}</h1><p className="text-sm sm:text-xl text-white/90">Result Portal</p></div></header>
        <div className="backdrop-blur-md bg-white/10 border border-white/20 rounded-2xl sm:rounded-3xl p-4 sm:p-8 shadow-2xl mb-4 sm:mb-8">
          <h2 className="text-lg sm:text-3xl font-bold text-white mb-4 sm:mb-6">Check Your Result</h2>
          <form onSubmit={handleSubmit} className="space-y-4 sm:space-y-6">
            <div><label className="block text-xs sm:text-sm font-medium text-white/90 mb-1.5 sm:mb-2">Select Class</label><select value={selectedClass} onChange={(e) => setSelectedClass(e.target.value)} className="w-full px-3 sm:px-4 py-2.5 sm:py-3 backdrop-blur-md bg-white/20 border border-white/30 rounded-lg sm:rounded-xl text-sm sm:text-base text-white placeholder-white/60 focus:outline-none focus:border-white/50 transition-all" required><option value="" className="text-gray-900">Choose your class</option>{Object.keys(CLASS_SUBJECTS).map((cls) => (<option key={cls} value={cls} className="text-gray-900">{cls}</option>))}</select></div>
            <div><label className="block text-xs sm:text-sm font-medium text-white/90 mb-1.5 sm:mb-2">Student Name</label><input type="text" value={studentName} onChange={(e) => setStudentName(e.target.value)} className="w-full px-3 sm:px-4 py-2.5 sm:py-3 backdrop-blur-md bg-white/20 border border-white/30 rounded-lg sm:rounded-xl text-sm sm:text-base text-white placeholder-white/60 focus:outline-none focus:border-white/50 transition-all" placeholder="Enter your name" required /></div>
            <button type="submit" disabled={loading} className="w-full py-3 sm:py-4 px-6 backdrop-blur-md bg-white/30 hover:bg-white/40 border border-white/40 rounded-lg sm:rounded-xl text-sm sm:text-base text-white font-semibold transition-all shadow-lg disabled:opacity-50">{loading ? 'Loading...' : 'CHECK RESULT'}</button>
          </form>
        </div>
        {error && (<div className="backdrop-blur-md bg-red-500/20 border border-red-400/40 rounded-2xl p-4 sm:p-6 mb-4 sm:mb-8"><p className="text-white text-center text-sm sm:text-base">{error}</p></div>)}
        {result && !error && (
          <>
            <div ref={resultRef} className="backdrop-blur-md bg-white/10 border border-white/20 rounded-2xl sm:rounded-3xl p-3 sm:p-8 shadow-2xl">
              <div className="text-center mb-3 sm:mb-6 pb-3 sm:pb-4 border-b border-white/20"><h3 className="text-lg sm:text-2xl font-bold text-white mb-0.5 sm:mb-1">{schoolName}</h3></div>
              <div className="text-center mb-4 sm:mb-6"><p className="text-base sm:text-xl text-white/90 font-semibold mb-2">{result.name || result.student_name}</p><div className="flex flex-col sm:flex-row justify-center gap-1.5 sm:gap-6"><span className="px-3 py-1.5 sm:px-4 sm:py-2 backdrop-blur-md bg-white/20 rounded-full text-xs sm:text-base text-white/90">Class: <strong>{result.class || result.class_name}</strong></span><span className="px-3 py-1.5 sm:px-4 sm:py-2 backdrop-blur-md bg-white/20 rounded-full text-xs sm:text-base text-white/90">Position: <strong>{result.position || '—'}</strong></span><span className="px-3 py-1.5 sm:px-4 sm:py-2 backdrop-blur-md bg-white/20 rounded-full text-xs sm:text-base text-white/90">Grade: <strong>{result.grade}</strong></span></div></div>
              <div className="backdrop-blur-md bg-white/5 border border-white/10 rounded-xl sm:rounded-2xl p-2 sm:p-6 mb-3 sm:mb-6 -mx-1 sm:mx-0"><table className="w-full text-xs sm:text-base"><thead><tr className="border-b border-white/20"><th className="text-left py-2 sm:py-3 px-1 text-white/90">Subject</th><th className="text-center py-2 sm:py-3 px-1 text-white/90 w-14 sm:w-auto">Marks</th><th className="text-center py-2 sm:py-3 px-1 text-white/90 w-14 sm:w-auto">Total</th></tr></thead><tbody>{result.subjects?.map((s: any, i: number) => (<tr key={i} className="border-b border-white/10"><td className="py-1.5 sm:py-2 px-1 text-white">{s.subject || s.name}</td><td className="text-center py-1.5 sm:py-2 px-1 text-white font-semibold">{s.obtained_marks || s.obtained}</td><td className="text-center py-1.5 sm:py-2 px-1 text-white/70">{s.total_marks || s.total}</td></tr>))}<tr className="border-t-2 border-white/30 bg-white/10"><td className="py-2 sm:py-3 px-1 text-white font-bold">TOTAL</td><td className="text-center py-2 sm:py-3 px-1 text-white font-bold">{result.total_obtained || result.subjects?.reduce((sum: number, s: any) => sum + (s.obtained_marks || s.obtained || 0), 0)}</td><td className="text-center py-2 sm:py-3 px-1 text-white/70 font-bold">{result.total_marks || result.subjects?.reduce((sum: number, s: any) => sum + (s.total_marks || s.total || 0), 0)}</td></tr></tbody></table></div>
              <div className="grid grid-cols-3 gap-2 sm:gap-4"><div className="backdrop-blur-md bg-white/20 border border-white/30 rounded-xl sm:rounded-2xl px-2 sm:px-4 py-2 sm:py-3 text-center"><p className="text-white/70 text-[10px] sm:text-xs mb-0.5">Percentage</p><p className="text-sm sm:text-2xl font-bold text-white">{typeof result.percentage === 'number' ? `${result.percentage.toFixed(2)}%` : result.percentage}</p></div><div className="backdrop-blur-md bg-white/20 border border-white/30 rounded-xl sm:rounded-2xl px-2 sm:px-4 py-2 sm:py-3 text-center"><p className="text-white/70 text-[10px] sm:text-xs mb-0.5">Grade</p><p className="text-sm sm:text-2xl font-bold text-white">{result.grade}</p></div><div className="backdrop-blur-md bg-white/20 border border-white/30 rounded-xl sm:rounded-2xl px-2 sm:px-4 py-2 sm:py-3 text-center"><p className="text-white/70 text-[10px] sm:text-xs mb-0.5">Remarks</p><p className="text-[10px] sm:text-sm font-bold text-white leading-tight">{result.remarks || 'Excellent'}</p></div></div>
            </div>
            <ResultActions studentName={result.name || result.student_name} schoolName={schoolName} percentage={typeof result.percentage === 'number' ? `${result.percentage.toFixed(2)}%` : result.percentage} grade={result.grade} resultRef={resultRef} variant="glass" />
          </>
        )}
      </main>
    </div>
  );
};
export default GlassmorphismPortal;
