import { useState, useRef } from 'react';import { toast } from 'sonner';import { CLASS_SUBJECTS } from '@/lib/classSubjects';import { generateDemoResult } from '@/lib/demoResults';import { Sparkles } from 'lucide-react';import BackButton from '@/components/portal/BackButton';import ResultActions from '@/components/portal/ResultActions';
interface PortalProps { isDemo?: boolean; schoolName?: string; logoUrl?: string | null; onSearch?: (c: string, s: string) => Promise<any>; demoResult?: any; }
const GradientModernPortal = ({ isDemo = true, schoolName = "Abbottabad Public School", logoUrl, onSearch, demoResult }: PortalProps) => {
  const [selectedClass, setSelectedClass] = useState('');const [studentName, setStudentName] = useState('');const [loading, setLoading] = useState(false);const [result, setResult] = useState<any>(demoResult || null);const [error, setError] = useState('');const resultRef = useRef<HTMLDivElement>(null);
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); if (!selectedClass || !studentName) { toast.error('Please select a class and enter your name'); return; } setLoading(true); setError(''); setResult(null); if (isDemo) { setTimeout(() => { setResult(generateDemoResult(studentName, selectedClass)); setLoading(false); toast.success('Result loaded!'); }, 1000); } else if (onSearch) { try { const r = await onSearch(selectedClass, studentName); if (r) { setResult(r); toast.success('Result loaded!'); } else setError('No result found.'); } catch { setError('Error occurred.'); } finally { setLoading(false); } } };
  const r = result; const sn = r?.name || r?.student_name; const cn = r?.class || r?.class_name;
  return (
    <div className="min-h-screen bg-gradient-to-br from-violet-600 via-fuchsia-500 to-pink-500 relative overflow-hidden">
      <PortalBranding variant="dark" /><BackButton variant="dark" />
      <main className="container mx-auto px-3 sm:px-4 pt-14 sm:pt-12 pb-20 max-w-3xl relative z-10">
        <header className="text-center mb-6 sm:mb-12"><div className="bg-gradient-to-r from-white/90 to-white/70 backdrop-blur-sm rounded-2xl sm:rounded-3xl p-4 sm:p-8 shadow-2xl">{logoUrl && <img src={logoUrl} alt={schoolName} className="h-20 w-20 mx-auto mb-4 rounded-full object-cover shadow-lg" />}<div className="flex items-center justify-center gap-2 sm:gap-3 mb-2 sm:mb-4"><Sparkles className="w-5 h-5 sm:w-8 sm:h-8 text-fuchsia-600" /><h1 className="text-xl sm:text-5xl font-extrabold bg-gradient-to-r from-violet-600 to-fuchsia-600 bg-clip-text text-transparent">{schoolName}</h1></div><p className="text-sm sm:text-xl text-gray-700">Result Portal</p></div></header>
        <div className="bg-white/90 backdrop-blur-sm rounded-2xl sm:rounded-3xl p-4 sm:p-8 shadow-2xl mb-4 sm:mb-8">
          <h2 className="text-lg sm:text-3xl font-bold bg-gradient-to-r from-violet-600 to-fuchsia-600 bg-clip-text text-transparent mb-4 sm:mb-6">Check Your Result</h2>
          <form onSubmit={handleSubmit} className="space-y-4 sm:space-y-6">
            <div><label className="block text-xs sm:text-sm font-semibold text-gray-700 mb-1.5 sm:mb-2">Select Class</label><select value={selectedClass} onChange={(e) => setSelectedClass(e.target.value)} className="w-full px-3 sm:px-4 py-2.5 sm:py-3 border-2 border-violet-200 rounded-lg sm:rounded-xl text-sm sm:text-base text-gray-900 focus:outline-none focus:border-fuchsia-500 transition-all shadow-sm" required><option value="">Choose your class</option>{Object.keys(CLASS_SUBJECTS).map((c) => (<option key={c} value={c}>{c}</option>))}</select></div>
            <div><label className="block text-xs sm:text-sm font-semibold text-gray-700 mb-1.5 sm:mb-2">Student Name</label><input type="text" value={studentName} onChange={(e) => setStudentName(e.target.value)} className="w-full px-3 sm:px-4 py-2.5 sm:py-3 border-2 border-violet-200 rounded-lg sm:rounded-xl text-sm sm:text-base text-gray-900 placeholder-gray-400 focus:outline-none focus:border-fuchsia-500 transition-all shadow-sm" placeholder="Enter your name" required /></div>
            <button type="submit" disabled={loading} className="w-full py-3 sm:py-4 px-6 bg-gradient-to-r from-violet-600 to-fuchsia-600 hover:from-violet-700 hover:to-fuchsia-700 text-sm sm:text-base text-white font-bold rounded-lg sm:rounded-xl transition-all shadow-lg disabled:opacity-50">{loading ? 'Loading...' : 'CHECK RESULT ✨'}</button>
          </form>
        </div>
        {error && (<div className="bg-red-100 border-2 border-red-400 rounded-2xl p-4 sm:p-6 mb-4 sm:mb-8 shadow-lg"><p className="text-red-800 text-center text-sm sm:text-base font-semibold">{error}</p></div>)}
        {r && !error && (
          <>
            <div ref={resultRef} className="bg-white/90 backdrop-blur-sm rounded-2xl sm:rounded-3xl p-3 sm:p-8 shadow-2xl">
              <div className="text-center mb-3 sm:mb-6 pb-3 sm:pb-4 border-b border-violet-200"><h3 className="text-base sm:text-xl font-bold text-violet-700 mb-0.5 sm:mb-1">{schoolName}</h3></div>
              <div className="text-center mb-4 sm:mb-8"><p className="text-lg sm:text-2xl text-gray-800 font-semibold mb-2 sm:mb-4">{sn}</p><div className="flex flex-col sm:flex-row justify-center gap-1.5 sm:gap-6"><span className="px-3 py-1.5 sm:px-4 sm:py-2 bg-gradient-to-r from-violet-100 to-fuchsia-100 rounded-full text-xs sm:text-base font-semibold text-violet-700">Class: {cn}</span><span className="px-3 py-1.5 sm:px-4 sm:py-2 bg-gradient-to-r from-violet-100 to-fuchsia-100 rounded-full text-xs sm:text-base font-semibold text-fuchsia-700">Position: {r.position || '—'}</span><span className="px-3 py-1.5 sm:px-4 sm:py-2 bg-gradient-to-r from-violet-100 to-fuchsia-100 rounded-full text-xs sm:text-base font-semibold text-pink-700">Grade: {r.grade}</span></div></div>
              <div className="bg-gradient-to-br from-violet-50 to-fuchsia-50 rounded-xl sm:rounded-2xl p-2 sm:p-6 mb-3 sm:mb-6 shadow-inner -mx-1 sm:mx-0"><table className="w-full text-xs sm:text-base"><thead><tr className="border-b-2 border-violet-300"><th className="text-left py-2 sm:py-3 px-1 text-violet-700 font-bold">Subject</th><th className="text-center py-2 sm:py-3 px-1 text-fuchsia-700 font-bold w-14 sm:w-auto">Marks</th><th className="text-center py-2 sm:py-3 px-1 text-pink-700 font-bold w-14 sm:w-auto">Total</th></tr></thead><tbody>{r.subjects?.map((s: any, i: number) => (<tr key={i} className="border-b border-violet-200"><td className="py-1.5 sm:py-3 px-1 text-gray-800 font-medium">{s.subject || s.name}</td><td className="text-center py-1.5 sm:py-3 px-1 text-fuchsia-600 font-bold">{s.obtained_marks || s.obtained}</td><td className="text-center py-1.5 sm:py-3 px-1 text-gray-600">{s.total_marks || s.total}</td></tr>))}<tr className="border-t-2 border-violet-300 bg-violet-100/50"><td className="py-2 sm:py-3 px-1 text-violet-800 font-bold">TOTAL</td><td className="text-center py-2 sm:py-3 px-1 text-fuchsia-700 font-bold">{r.total_obtained || r.subjects?.reduce((sum: number, s: any) => sum + (s.obtained_marks || s.obtained || 0), 0)}</td><td className="text-center py-2 sm:py-3 px-1 text-gray-600 font-bold">{r.total_marks || r.subjects?.reduce((sum: number, s: any) => sum + (s.total_marks || s.total || 0), 0)}</td></tr></tbody></table></div>
              <div className="grid grid-cols-3 gap-2 sm:gap-4"><div className="bg-gradient-to-r from-violet-600 to-fuchsia-600 rounded-xl sm:rounded-2xl p-2 sm:p-4 text-center"><p className="text-white/80 text-[10px] sm:text-xs mb-0.5">Percentage</p><p className="text-sm sm:text-2xl font-bold text-white">{typeof r.percentage === 'number' ? `${r.percentage.toFixed(2)}%` : r.percentage}</p></div><div className="bg-gradient-to-r from-fuchsia-600 to-pink-600 rounded-xl sm:rounded-2xl p-2 sm:p-4 text-center"><p className="text-white/80 text-[10px] sm:text-xs mb-0.5">Grade</p><p className="text-sm sm:text-2xl font-bold text-white">{r.grade}</p></div><div className="bg-gradient-to-r from-pink-600 to-rose-600 rounded-xl sm:rounded-2xl p-2 sm:p-4 text-center"><p className="text-white/80 text-[10px] sm:text-xs mb-0.5">Remarks</p><p className="text-[10px] sm:text-sm font-bold text-white leading-tight">{r.remarks || 'Excellent'}</p></div></div>
            </div>
            <ResultActions studentName={sn} schoolName={schoolName} percentage={typeof r.percentage === 'number' ? `${r.percentage.toFixed(2)}%` : r.percentage} grade={r.grade} resultRef={resultRef} variant="gradient" />
          </>
        )}
      </main>
    </div>
  );
};
export default GradientModernPortal;
